"""empty message

Revision ID: 2cef570d1f7e
Revises: f0592ccfccca
Create Date: 2021-05-17 11:40:31.053249+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cef570d1f7e'
down_revision = 'f0592ccfccca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.String(length=32), nullable=False, default=1))
        batch_op.drop_constraint('author_id', type_='foreignkey')
        batch_op.create_foreign_key('author_id', 'users', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_constraint('author_id', type_='foreignkey')
        batch_op.create_foreign_key('author_id', 'users', ['author'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
