"""Attempt to fix issues with database

Revision ID: 5562577e4f0d
Revises: 223473d635a0
Create Date: 2021-04-26 09:39:53.177178+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5562577e4f0d'
down_revision = '223473d635a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('url_slug', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint('url_slug_unique', ['url_slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('url_slug_unique', type_='unique')
        batch_op.drop_column('url_slug')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
