"""Add foreign keys for story and chapter models

Revision ID: 5df368b5a5b6
Revises: 96511d6f5bb8
Create Date: 2021-05-05 11:11:13.576083+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df368b5a5b6'
down_revision = '96511d6f5bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_foreign_key('author_id', 'users', ['author'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_constraint('author_id', type_='foreignkey')

    # ### end Alembic commands ###
