"""Add category mechanism to story model

Revision ID: 7dc81465810b
Revises: b8015e18f6df
Create Date: 2021-04-23 16:39:24.105182+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc81465810b'
down_revision = 'b8015e18f6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('categories_url_slug', ['url_slug'])
        batch_op.drop_column('short_name')

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('categories')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.VARCHAR(length=4), nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
