"""Add created_at and updated_at to Story and User models

Revision ID: 96511d6f5bb8
Revises: bfdb6a89a45c
Create Date: 2021-05-05 10:33:52.249985+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96511d6f5bb8'
down_revision = 'bfdb6a89a45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.String(length=48), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.String(length=48), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
