"""Add url_slug to category

Revision ID: f0592ccfccca
Revises: 6e659c9e4f4b
Create Date: 2021-05-11 10:11:57.391950+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0592ccfccca'
down_revision = '6e659c9e4f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('url_slug_unique', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_categories_id'), ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_categories_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_categories_url_slug'), ['url_slug'])

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_constraint('stories_url_slug', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_stories_url_slug'), ['url_slug'])

    with op.batch_alter_table('story_chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_slug', sa.String(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_story_chapters_id'), ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_story_chapters_url_slug'), ['url_slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_chapters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_story_chapters_url_slug'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_story_chapters_id'), type_='unique')
        batch_op.drop_column('url_slug')

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_stories_url_slug'), type_='unique')
        batch_op.create_unique_constraint('stories_url_slug', ['url_slug'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_url_slug'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_categories_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_categories_id'), type_='unique')
        batch_op.create_unique_constraint('url_slug_unique', ['url_slug'])

    # ### end Alembic commands ###
